name = "RichRopes"
uuid = "5b289667-34e7-400b-b197-4c1a14d08939"
authors = ["Sam Atman <atmanistan@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[compat]
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
